server:
  port: 8000
  mode: debug
  enable: true

log:
  target: console

mysql:
  enable: false
  dbName: 8-pigeons
  user: 8-pigeons
  pwd: "123456"
  host: 127.0.0.1:3306
  tablePrefix: dr_
  charset: utf8mb4
  parseTime: true
  maxIdleConns: 10 #最大空闲连接数
  maxOpenConns: 50 #最大打开连接数

redis:
  enable: false #是否开启
  network: tcp    #协议
  addr: 127.0.0.1 #地址
  port: 6379      #端口
  password: ""   #密码
  DB: 1           #数据库

  #连接池容量及闲置连接数量
  poolSize: 15 # 连接池最大socket连接数，默认为4倍CPU数， 4 * runtime.NumCPU
  minIdleConns: 10 #在启动阶段创建指定数量的Idle连接，并长期维持idle状态的连接数不少于指定数量；。

  #超时
  dialTimeout: 5  #连接建立超时时间，默认5秒。
  readTimeout: 3  #读超时，默认3秒， -1表示取消读超时
  writeTimeout: 3  #写超时，默认等于读超时
  poolTimeout: 4  #当所有连接都处在繁忙状态时，客户端等待可用连接的最大等待时长，默认为读超时+1秒。

  #闲置连接检查包括IdleTimeout，MaxConnAge
  idleCheckFrequency: 60 #闲置连接检查的周期，默认为1分钟，-1表示不做周期性检查，只在客户端获取连接时对闲置连接进行处理。
  idleTimeout: 5  #闲置超时，默认5分钟，-1表示取消闲置超时检查
  maxConnAge: 0   #连接存活时长，从创建开始计时，超过指定时长则关闭连接，默认为0，即不关闭存活时长较长的连接

  #命令执行失败时的重试策略
  maxRetries: 0   # 命令执行失败时，最多重试多少次，默认为0即不重试
  minRetryBackoff: 8   #每次计算重试间隔时间的下限，默认8毫秒，-1表示取消间隔
  maxRetryBackoff: 512 #每次计算重试间隔时间的上限，默认512毫秒，-1表示取消间隔